# TP 6: Numpy

NumPy est le package fondamental pour le calcul scientifique en Python. Il s'agit d'une bibliothèque Python qui fournit un objet tableau multidimensionnel, divers objets dérivés (tels que des tableaux masqués et des matrices) et un assortiment de routines pour des opérations rapides sur des tableaux, y compris mathématiques, logiques, manipulation de forme, tri, sélection, E/S , transformées de Fourier discrètes, algèbre linéaire de base, opérations statistiques de base, simulation aléatoire et bien plus encore.

Pour accéder à NumPy et à ses fonctions, importez-le dans votre code Python comme ceci :



In [1]:
import numpy as np

Nous raccourcissons le nom importé en np pour une meilleure lisibilité du code à l'aide de NumPy. Il s'agit d'une convention largement adoptée que vous devez suivre afin que toute personne travaillant avec votre code puisse facilement la comprendre.

## Générateurs de tableaux **ndarray**


La méthode la plus simple pour créer un tableau NumPy est de partir d'une liste Python existante. Vous pouvez utiliser la fonction `numpy.array()` pour convertir une liste en un tableau NumPy.

```python
import numpy as np

# Création d'un tableau NumPy à partir d'une liste
ma_liste = [1, 2, 3, 4, 5]
mon_tableau = np.array(ma_liste)
```

###  Création de Tableaux NumPy avec des Valeurs Initiales

Vous pouvez également créer un tableau NumPy avec des valeurs initiales en utilisant des fonctions spécifiques de NumPy. Par exemple, la fonction `numpy.zeros()` crée un tableau rempli de zéros, tandis que `numpy.ones()` crée un tableau rempli de uns.

```python
# Création d'un tableau rempli de zéros
tableau_zeros = np.zeros((3, 4))  # Un tableau de forme (3, 4)

# Création d'un tableau rempli de uns
tableau_ones = np.ones((2, 2))  # Un tableau de forme (2, 2)
```

### Création de Séquences Numériques

NumPy propose des fonctions pour créer des séquences numériques régulières. Par exemple, vous pouvez utiliser `numpy.arange()` pour générer une séquence de nombres espacés de manière régulière.

```python
# Création d'une séquence de nombres de 0 à 9
sequence = np.arange(10)  # Les nombres vont de 0 à 9
```

### Génération de Nombres Aléatoires

Pour créer des tableaux NumPy avec des nombres aléatoires, NumPy propose le module `numpy.random`. Vous pouvez utiliser `numpy.random.rand()` pour générer des nombres aléatoires dans une distribution uniforme entre 0 et 1.

```python
# Génération de nombres aléatoires entre 0 et 1
nombres_aleatoires = np.random.rand(3, 3)  # Un tableau 3x3 de nombres aléatoires
```




In [2]:
A = np.array([1, 2, 3]) # générateur par défaut, qui permet de convertir des listes (ou autres objets) en tableau ndarray
A = np.zeros((2, 3)) # tableau de 0 aux dimensions 2x3
B = np.ones((2, 3)) # tableau de 1 aux dimensions 2x3
np.random.seed(0)
C = np.random.randn(2, 3) # tableau aléatoire (distribution normale) aux dimensions 2x3
D = np.random.rand(2, 3) # tableau aléatoire (distribution uniforme)
size = (2, 3)
E = np.random.randint(0, 10, size) # tableau d'entiers aléatoires de 0 a 10 et de dimension 2x3
B = np.eye(4, dtype=bool) # créer une matrice identité et convertit les éléments en type bool.


In [3]:
A = np.linspace(0,5, 20) # np.linspace(start,end, number of elements)
B = np.arange(0, 5, 0.5) # np.linspace(start,end, step)
print(A)
print(B)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [7]:
A = np.linspace(5, 10,7, dtype=np.float16) # définit le type et la place a occuper sur la mémoire
print("float16: ",A)
A = np.linspace(5,10,7, dtype=np.float32)
print("float32: ",A)
A = np.linspace(5,10,7, dtype=np.float64)
print("float64: ",A)

float16:  [ 5.     5.832  6.668  7.5    8.336  9.164 10.   ]
float32:  [ 5.         5.8333335  6.6666665  7.5        8.333333   9.166667
 10.       ]
float64:  [ 5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.        ]


## Attributs importants

In [8]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
print(A.size) # le nombre d'éléments dans le tableau A
print(A.shape) # les dimensions du tableau A (sous forme de Tuple)
print(type(A.shape)) # voici la preuve que la shape est un tuple
print(A.shape[0]) # le nombre d'éléments dans la premiere dimension de A

6
(2, 3)
<class 'tuple'>
2


## Méthodes importantes

###  **reshape() : Redimensionner un Tableau**

La fonction `reshape()` de NumPy permet de modifier la forme d'un tableau existant sans changer les données qu'il contient. Elle est utilisée pour transformer un tableau multi-dimensionnel en une forme différente tout en maintenant le même nombre total d'éléments.

```python

# Création d'un tableau de forme (4, 3)
tableau_original = np.arange(12).reshape(4, 3)

# Redimensionnement en un tableau de forme (3, 4)
tableau_redimensionné = tableau_original.reshape(3, 4)
```

La fonction `reshape()` est utile lorsque vous avez besoin de changer la structure d'un tableau NumPy pour qu'il corresponde aux exigences d'une opération spécifique.

###  **ravel() : Aplatir un Tableau**

La fonction `ravel()` est utilisée pour aplatir un tableau multidimensionnel en un tableau à une seule dimension. Elle crée une vue du tableau original, ce qui signifie que les données ne sont pas copiées, mais elles sont simplement réorganisées pour former une seule dimension.

```python
import numpy as np

# Création d'un tableau multidimensionnel
tableau_original = np.array([[1, 2, 3], [4, 5, 6]])

# Aplatir le tableau en un tableau à une dimension
tableau_aplati = tableau_original.ravel()
```

L'utilisation de `ravel()` est courante lorsque vous avez besoin de travailler avec des données sous forme de tableau à une seule dimension, par exemple lors de l'application de certaines opérations mathématiques.

###  **squeeze() : Supprimer les Dimensions Unitaires**

La fonction `squeeze()` est utilisée pour supprimer les dimensions qui ont une taille de 1 dans un tableau NumPy. Elle permet de simplifier la structure du tableau en éliminant les dimensions inutiles.

```python
import numpy as np

# Création d'un tableau avec une dimension unitaire
tableau_original = np.array([[[1, 2, 3]]])

# Suppression de la dimension unitaire
tableau_squeezé = np.squeeze(tableau_original)
```

L'utilisation de `squeeze()` est utile lorsque vous avez des dimensions inutiles dans votre tableau et que vous souhaitez les éliminer pour simplifier le tableau.

###  **concatenate() : Assembler des Tableaux**

La fonction `concatenate()` de NumPy permet d'assembler deux tableaux le long d'un axe spécifié. Vous pouvez choisir l'axe le long duquel les tableaux seront concaténés (0 pour les lignes, 1 pour les colonnes, etc.).

```python
import numpy as np

# Création de deux tableaux
tableau1 = np.array([[1, 2], [3, 4]])
tableau2 = np.array([[5, 6]])

# Concaténation le long de l'axe des colonnes (axis=1)
tableau_concaténé = np.concatenate((tableau1, tableau2.T), axis=1)
```

La fonction `concatenate()` est utile lorsque vous avez besoin de fusionner deux tableaux NumPy le long d'un axe spécifié pour former un nouveau tableau.



In [9]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
A = A.reshape((3, 2)) # redimensionne le tableau A (3 lignes, 2 colonnes)
print("reshape: ",A)
B = A.ravel() # Aplatit le tableau A (une seule dimension)
print("ravel: ",B)

reshape:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
ravel:  [0. 0. 0. 0. 0. 0.]


In [10]:
A= np.array([1,2,5,3])
print(A)
print(A.shape)

A= A.reshape((A.shape[0],1))
print(A.shape)

A=A.squeeze()
print(A.shape)

[1 2 5 3]
(4,)
(4, 1)
(4,)




###  `concatenate()`

La fonction `concatenate()` en NumPy est une fonction polyvalente utilisée pour concaténer deux tableaux ou plus le long d'un axe spécifié. Vous pouvez spécifier l'axe le long duquel les tableaux doivent être concaténés. Par défaut, elle concatène le long de l'axe 0 (les lignes), créant un tableau plus grand.

```python
import numpy as np

# Création de deux tableaux
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concaténation le long de l'axe 0 (les lignes)
result = np.concatenate((arr1, arr2))
```

Dans cet exemple, `result` sera `[1, 2, 3, 4, 5, 6]`.

Vous pouvez également spécifier explicitement l'axe, comme ceci :

```python
result = np.concatenate((arr1, arr2), axis=0)
```

###  `vstack()`

La fonction `vstack()` est une fonction spécialisée pour l'empilement vertical des tableaux, ce qui signifie qu'elle empile les tableaux les uns au-dessus des autres le long de l'axe 0 (les lignes). Elle est équivalente à l'utilisation de `concatenate()` avec `axis=0`.

```python
import numpy as np

# Création de deux tableaux
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Empilement vertical des tableaux
result = np.vstack((arr1, arr2))
```

Dans cet exemple, `result` sera :
```
array([[1, 2],
       [3, 4],
       [5, 6]])
```

###  `hstack()`

La fonction `hstack()` est utilisée pour l'empilement horizontal des tableaux, ce qui signifie qu'elle empile les tableaux côte à côte le long de l'axe 1 (les colonnes). Elle est équivalente à l'utilisation de `concatenate()` avec `axis=1`.

```python
import numpy as np

# Création de deux tableaux
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

# Empilement horizontal des tableaux
result = np.hstack((arr1, arr2))
```

Dans cet exemple, `result` sera :
```
array([[1, 2, 5],
       [3, 4, 6]])
```

`vstack()` et `hstack()` sont souvent utilisées lorsque vous avez des tableaux avec des formes compatibles et que vous souhaitez les combiner dans une direction spécifique sans spécifier explicitement l'axe.



In [11]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
B = np.ones((2, 3)) # création d'un tableau de shape (2, 3)

np.concatenate((A, B), axis=0) # axe 0 : équivalent de np.vstack((A, B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.concatenate((A, B), axis=1) # axe 1 : équivalent de np.hstack((A, B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [8]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
B = np.ones((2, 3)) # création d'un tableau de shape (2, 3)
C = np.hstack((A,B))
print(C)
print(C.shape)



[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
(2, 6)


In [9]:
C = np.vstack((A,B))
print(C)
print(C.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
(4, 3)


## Slicing et Indexing


### Indexing (Indexation)

L'indexation en NumPy consiste à accéder à des éléments spécifiques d'un tableau en utilisant des indices. Les indices sont utilisés pour cibler des éléments individuels ou des sous-tableaux en fonction de leur position dans le tableau.

Par exemple, pour accéder à un élément spécifique d'un tableau, vous utilisez un ou plusieurs indices entre crochets :

```python
import numpy as np

# Création d'un tableau NumPy
tableau = np.array([1, 2, 3, 4, 5])

# Accès à un élément individuel par son index
element = tableau[2]  # Accède à l'élément à l'index 2 (valeur 3)
```

L'indexation en NumPy commence toujours à 0, donc l'élément à l'index 2 est le troisième élément du tableau.

### Slicing (Découpage)

Le "slicing" en NumPy permet d'extraire des parties spécifiques d'un tableau en spécifiant une plage d'indices. Il est utilisé pour obtenir des sous-tableaux à partir d'un tableau plus grand.

Le "slicing" se fait en utilisant la notation avec deux points `:` entre les indices de début et de fin. Par exemple, pour extraire une partie d'un tableau :

```python
import numpy as np

# Création d'un tableau NumPy
tableau = np.array([1, 2, 3, 4, 5])

# Extraction d'une sous-partie du tableau
sous_tableau = tableau[1:4]  # Extrait les éléments de l'index 1 à 3 inclus (valeurs 2, 3, 4)
```

Dans cet exemple, `sous_tableau` contiendra `[2, 3, 4]`. Le premier indice est inclus, tandis que le second indice est exclu.

Le "slicing" en NumPy peut également être utilisé avec des tableaux multidimensionnels pour extraire des sous-tableaux de manière similaire le long de plusieurs axes.


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [14]:
# Pour acceder a la ligne 0, colonne 1
A[0, 1] 

10

In [16]:
# Pour selectionner les blocs de la ligne (0-1) colonne (0-1)
A[0:2, 0:2]

array([[10, 10],
       [10, 10]])

In [17]:
A[0:2, 0:2] = 10
print(A)

[[10 10  3]
 [10 10  6]]


## Boolean Indexing




L'indexation booléenne est une technique puissante en NumPy qui permet de filtrer et d'extraire des éléments d'un tableau en se basant sur des conditions logiques. Cette méthode repose sur l'utilisation de tableaux de valeurs booléennes pour sélectionner les éléments qui satisfont une condition spécifique.

### Création d'un Tableau Booléen

Pour effectuer une indexation booléenne, vous commencez par créer un tableau de valeurs booléennes en appliquant une condition à un tableau existant. Par exemple, pour créer un tableau booléen indiquant les éléments supérieurs à 5 dans un tableau `tableau` :

```python
import numpy as np

# Création d'un tableau NumPy
tableau = np.array([1, 7, 3, 9, 4, 8])

# Création d'un tableau booléen en appliquant une condition
tableau_bool = tableau > 5  # Crée un tableau booléen avec True pour les valeurs > 5
```

Dans cet exemple, `tableau_bool` contiendra `[False, True, False, True, False, True]`.

### Indexation à l'aide du Tableau Booléen

Une fois que vous avez créé un tableau booléen, vous pouvez l'utiliser pour extraire les éléments correspondants du tableau d'origine. Vous placez simplement le tableau booléen entre crochets pour effectuer la sélection. Les éléments associés à `True` seront extraits.

```python
# Indexation à l'aide du tableau booléen
resultat = tableau[tableau_bool]  # Sélectionne les éléments > 5

# Affichage du résultat
print(resultat)  # Affichera [7, 9, 8]
```

L'indexation booléenne permet de filtrer rapidement et efficacement les données dans un tableau en fonction de conditions complexes. Elle est largement utilisée dans le traitement de données et l'analyse pour extraire des sous-ensembles spécifiques de données qui répondent à des critères spécifiques.



In [16]:
A = np.array([[1, 2, 3], [4, 5, 6]])
 
print(A<5) # masque booléen
 
print(A[A < 5]) # sous-ensemble filtré par le masque booléen
 
A[A<5] = 4 # convertit les valeurs sélectionnées.
print(A)

[[ True  True  True]
 [ True False False]]
[1 2 3 4]
[[4 4 4]
 [4 5 6]]


## Numpy : Mathématiques

### Méthodes de bases (les plus utiles) de la classe ndarray

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print("la somme des elements",A.sum()) # effectue la somme de tous les éléments du tableau
print("la somme des elements colone",A.sum(axis=0)) # effectue la somme des colonnes (somme sur éléments des les lignes)
print("la somme des elements ligne",A.sum(axis=1)) # effectue la somme des lignes (somme sur les éléments des colonnes)
print("la somme cumulative",A.cumsum(axis=0)) # effectue la somme cumulée
 
print(A.prod()) # effectue le produit
print(A.cumprod()) # effectue le produit cumulé
 
print(A.min()) # trouve le minimum du tableau
print(A.max()) # trouve le maximum du tableau
 
print(A.mean()) # calcule la moyenne
print(A.std()) # calcule l'ecart type,
print(A.var()) # calcule la variance

[[1 2 3]
 [4 5 6]]
la somme des elements 21
la somme des elements colone [5 7 9]
la somme des elements ligne [ 6 15]
la somme cumulative [[1 2 3]
 [5 7 9]]
720
[  1   2   6  24 120 720]
1
6
3.5
1.707825127659933
2.9166666666666665


Une méthode tres importante : la méthode **argsort()**

In [19]:
A = np.random.randint(0, 10, [5, 5]) # tableau aléatoire
print(A)

[[4 2 6 2 4]
 [7 7 4 0 1]
 [6 6 6 3 3]
 [2 0 7 7 3]
 [5 7 4 9 7]]


In [20]:
print(A.argsort()) # retourne les index pour trier chaque ligne du tableau 

[[1 3 0 4 2]
 [3 4 2 0 1]
 [3 4 0 1 2]
 [1 0 4 2 3]
 [2 0 1 4 3]]


In [21]:
print(A[:,0].argsort()) # retourne les index pour trier la colonne 0 de A

[3 0 4 2 1]


In [22]:
A = A[A[:,0].argsort(), :] # trie les colonnes du tableau selon la colonne 0.
A

array([[2, 0, 7, 7, 3],
       [4, 2, 6, 2, 4],
       [5, 7, 4, 9, 7],
       [6, 6, 6, 3, 3],
       [7, 7, 4, 0, 1]])

### Numpy Statistics


In [ ]:
B = np.random.randn(3, 3) # nombres aléatoires 3x3
 
# retourne la matrice de corrélation de B
print(np.corrcoef(B))

[[ 1.         -0.63427277  0.99937797]
 [-0.63427277  1.         -0.66114251]
 [ 0.99937797 -0.66114251  1.        ]]


In [24]:
# retourne la matrice de corrélation entre les lignes 0 et 1 de B
print(np.corrcoef(B[:,0], B[:, 1]))

[[1.         0.81847981]
 [0.81847981 1.        ]]


np.unique() :

In [4]:
np.random.seed(0)
A = np.random.randint(0, 5, [5,5])
A

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0],
       [1, 1, 0, 1, 4],
       [3, 0, 3, 0, 2]])

In [16]:
np.unique(A)

array([0, 1, 2, 3, 4])

In [5]:
values, counts = np.unique(A, return_counts=True)
print(values, counts)
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

[0 1 2 3 4] [7 5 3 6 4]
valeur 2 apparait 3
valeur 4 apparait 4
valeur 1 apparait 5
valeur 3 apparait 6
valeur 0 apparait 7


Calculs statistiques en présence de données manquates (NaN)

In [36]:
A = np.random.randn(5, 5)
A[0, 2] = np.nan # insere un NaN dans la matrice A
 
print('ratio NaN/zise:', (np.isnan(A).sum()/A.size)) # calcule la proportion de NaN dans A
 
print('moyenne sans NaN:', np.nanmean(A)) # calcule la moyenne de A en ignorant les NaN

ratio NaN/zise: 0.04
moyenne sans NaN: 0.1832816316588837


### Algebre Linéaire

In [38]:
A = np.ones((2,3))
B = np.ones((3,3))

print(A.T) # transposé de la matrice A (c'est un attribut de ndarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
print(A.dot(B)) # produit matriciel A.B

[[3. 3. 3.]
 [3. 3. 3.]]


In [45]:
A = np.random.randint(0, 10, [3, 3])
 
print('det=', np.linalg.det(A)) # calcule le determinant de A
print('inv A:\n', np.linalg.inv(A)) # calcul l'inverse de A

det= 61.00000000000001
inv A:
 [[ 0.08196721  0.63934426 -0.60655738]
 [-0.13114754 -0.62295082  0.7704918 ]
 [ 0.21311475  0.26229508 -0.37704918]]


In [44]:
val, vec = np.linalg.eig(A)
print('valeur propre:\n', val) # valeur propre
print('vecteur propre:\n', vec) # vecteur propre

valeur propre:
 [ 8.91371956 -0.86320273  1.94948316]
vecteur propre:
 [[-0.27183844 -0.6838339   0.39494311]
 [-0.4097407  -0.15279739 -0.73291062]
 [-0.87075623  0.71345929  0.55395123]]


### Fonctions mathématiques

In [13]:
A = np.linspace(1,10,10)
print(np.exp(A)) # calclule l'exponontielle pour tous les element d'un tableau
print(np.log(A)) # calclule le logaritheme pour tous les element d'un tableau
print(np.cos(A)) # calclule le cosinus pour tous les element d'un tableau
print(np.sin(A)) # calclule le sinus pour tous les element d'un tableau

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


## Exercices

1. Array Creation and Manipulation:
Create a NumPy array of shape (3, 4) filled with random integers between 1 and 10. Then, reshape it into a (2, 6) array.

2. Array Concatenation:
Create two NumPy arrays of the same shape (3, 3) filled with random numbers. Concatenate them vertically using vstack() and horizontally using hstack().

3. Indexing and Slicing:
Create a NumPy array of shape (5, 5) filled with sequential integers from 1 to 25. Use array indexing and slicing to extract the middle 3x3 subarray.

4. Array Operations:
Create a NumPy array of shape (4, 4) filled with random integers. Calculate the sum, mean, and standard deviation of the array's elements.

5. Boolean Indexing:
Create a NumPy array of random integers between 1 and 100. Use boolean indexing to extract all values greater than 50.


6. Sur l'image ci dessous, effectuer un slicing pour ne garder que la moitié de l'image (en son centre) et remplacer tous les pixels > 150 par des 

In [ ]:
pixels = 255
from scipy import misc
import matplotlib.pyplot as plt
face = misc.face(gray=True)
plt.imshow(face, cmap=plt.cm.gray)
plt.show()
face.shape

7. Standardisez la matrice suivante, c'est a dire effectuez le calcul suivant :
$A = \frac{A - mean(A_{colonne})}{std(A_{colonne})}$

In [ ]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A